version: '3.2'
volumes:
  logs:
    driver: local
  vendor:
    driver: local
services:
  app_server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
